name: Lint Commit Messages

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  commit-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v4
        with:
          configFile: .github/.commitlintrc.json
