name: Lint Commit Messages

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  commit-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Fetch all tags
        run: git fetch --tags

      - name: Lint Commit Messages
        id: commitlint
        uses: wagoid/commitlint-github-action@v4
        continue-on-error: true
        with:
          configFile: .github/.commitlintrc.json

      - name: Provide feedback if commit messages are invalid
        if: failure()
        run: |
          echo "Please follow Conventional Commits guidelines for commit messages." > feedback.txt
          echo "The proper format is:" >> feedback.txt
          echo "<type>(<scope>): <subject>" >> feedback.txt
          echo "" >> feedback.txt
          echo "Example: feat(parser): add ability to parse arrays" >> feedback.txt

          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            gh pr comment ${{ github.event.pull_request.number }} --body-file feedback.txt
          else
            echo "This is not a pull request event."
          fi
